export const creators = [
  {
    id: 1,
    name: 'Halyna',
    surname: 'Kravchenko',
    linkedinLink: 'https://www.linkedin.com/in/halyna-kravchenko-451172291/',
    githubLink: 'https://github.com/minimal005',
    avatar: './img/creators/halyna.jpg',
    hobby: 'Handmade, Reading, Travelling.',
  },
  {
    id: 2,
    name: 'Anastasiia',
    surname: 'Pogorielova',
    linkedinLink: 'https://www.linkedin.com/in/anastasiia-pogorielova/',
    githubLink: 'https://github.com/pogorielova',
    avatar: './img/creators/fantomas.png',
    hobby: 'Dog Training, Communication.',
  },
  {
    id: 3,
    name: 'Maksym',
    surname: 'Seliutin',
    linkedinLink: 'https://www.linkedin.com/in/maksym-seliutin/',
    githubLink: 'https://github.com/MakksymSly',
    avatar: './img/creators/maksym.jpg',
    hobby: 'Mechanics, Gaming, Fishing.',
  },
  {
    id: 4,
    name: 'Andrii',
    surname: 'Mekshun',
    linkedinLink: 'https://www.linkedin.com/in/andrii-mekshun-43524a297/',
    githubLink: 'https://github.com/Welbrn',
    avatar: './img/creators/Andrii.jpg',
    hobby: 'Gaming, PC building, Music',
  },
  {
    id: 5,
    name: 'xxxxxxx',
    surname: 'xxxxxxx',
    linkedinLink: 'https://www.linkedin.com/in/maksym-seliutin/',
    githubLink: 'https://github.com/MakksymSly',
    avatar: './img/creators/fantomas.png',
    hobby: 'xxxxxxx',
  },
];
